-- MySQL Script generated by MySQL Workbench
-- 10/17/16 10:53:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema baseparqueadero
-- -----------------------------------------------------
-- Esta es la base de datos para el parqueadero

-- -----------------------------------------------------
-- Schema baseparqueadero
--
-- Esta es la base de datos para el parqueadero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `baseparqueadero` DEFAULT CHARACTER SET utf8 ;
USE `baseparqueadero` ;

-- -----------------------------------------------------
-- Table `baseparqueadero`.`vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseparqueadero`.`vehiculo` (
  `idvehiculo` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(1) NOT NULL,
  `placa` VARCHAR(10) NOT NULL,
  `marca` VARCHAR(15) NULL,
  `modelo` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  `color` VARCHAR(20) NULL,
  `propietario` VARCHAR(45) NULL,
  `estado` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idvehiculo`),
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseparqueadero`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseparqueadero`.`persona` (
  `idpersona` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidop` VARCHAR(45) NOT NULL,
  `apellidom` VARCHAR(45) NULL,
  `tipo_id` VARCHAR(15) NOT NULL,
  `num_id` VARCHAR(15) NOT NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `celular` INT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idpersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseparqueadero`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseparqueadero`.`trabajador` (
  `idpersona` INT NOT NULL,
  `sueldo` DECIMAL(7,2) NOT NULL,
  `acceso` VARCHAR(20) NOT NULL,
  `login` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(1) NOT NULL,
  `contrato` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idpersona`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  CONSTRAINT `fk_persona_trabajador`
    FOREIGN KEY (`idpersona`)
    REFERENCES `baseparqueadero`.`persona` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseparqueadero`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseparqueadero`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `idvehiculo` INT NOT NULL,
  `idtrabajador` INT NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_salida` DATE NULL,
  `dia_i` INT NOT NULL,
  `mes_i` INT NOT NULL,
  `ano_i` INT NOT NULL,
  `hora_i` INT NOT NULL,
  `minuto_i` INT NOT NULL,
  `dia_s` INT NULL,
  `mes_s` INT NULL,
  `ano_s` INT NULL,
  `hora_s` INT NULL,
  `minuto_s` INT NULL,
  `tiempo_total` INT NULL,
  `valor_min` DECIMAL(7,2) NOT NULL,
  `valor_total` DECIMAL(7,2) NULL,
  `estado_V` VARCHAR(1) NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_reserva_trabajador_idx` (`idtrabajador` ASC),
  INDEX `fk_reserva_vehiculo_idx` (`idvehiculo` ASC),
  CONSTRAINT `fk_reserva_trabajador`
    FOREIGN KEY (`idtrabajador`)
    REFERENCES `baseparqueadero`.`trabajador` (`idpersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_vehiculo`
    FOREIGN KEY (`idvehiculo`)
    REFERENCES `baseparqueadero`.`vehiculo` (`idvehiculo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `baseparqueadero`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `baseparqueadero`.`pago` (
  `idpago` INT NOT NULL AUTO_INCREMENT,
  `idreserva` INT NOT NULL,
  `tipo_comprobante` VARCHAR(20) NOT NULL,
  `num_comprobante` VARCHAR(20) NOT NULL,
  `fecha_pago` DATE NOT NULL,
  `subtotal` DECIMAL(7,2) NOT NULL,
  `iva` DECIMAL(7,2) NOT NULL,
  `total_pago` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_reserva_idx` (`idreserva` ASC),
  CONSTRAINT `fk_pago_reserva`
    FOREIGN KEY (`idreserva`)
    REFERENCES `baseparqueadero`.`reserva` (`idreserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
